name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-codenomads"
database_id = "80ab97c6-177c-47fa-b9f1-eb07d5683975"
